tinyMCE.addI18n('eu.style_dlg',{
title:"Aldatu CSS estiloa",
apply:"Apikatu",
text_tab:"Testua",
background_tab:"Atzea",
block_tab:"Block",
box_tab:"Box",
border_tab:"Border",
list_tab:"Zerrenda",
positioning_tab:"Kokapena",
text_props:"Testua",
text_font:"Letra-tipoa",
text_size:"Tamaina",
text_weight:"Weight",
text_style:"Estiloa",
text_variant:"Aldaera",
text_lineheight:"Lerro garaiera",
text_case:"Minus./Maius.",
text_color:"Kolorea",
text_decoration:"Apaingarriak",
text_overline:"Goimarra",
text_underline:"Azpimarra",
text_striketrough:"Marratua",
text_blink:"Keinada",
text_none:"Bat ere ez",
background_color:"Atzeko kolorea",
background_image:"Atzeko irudia",
background_repeat:"Errepikatu",
background_attachment:"Eranskina",
background_hpos:"Posizio horizontala",
background_vpos:"Posizio bertikala",
block_wordspacing:"Hitz banaketa",
block_letterspacing:"Letra banaketa",
block_vertical_alignment:"Lerrokatze bertikala",
block_text_align:"Testu lerrokatzea",
block_text_indent:"Koska",
block_whitespace:"Zuriunea",
block_display:"Erakutsi",
box_width:"Zabalera",
box_height:"Altuera",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Guztientzat berdina",
top:"Gora",
right:"Eskuina",
bottom:"Behera",
left:"Ezkerra",
margin:"Margina",
style:"Estiloa",
width:"Zabalera",
height:"Altuera",
color:"Kolorea",
list_type:"Mota",
bullet_image:"Bulet-irudia",
position:"Kokapena",
positioning_type:"Mora",
visibility:"Ikusgarritasuna",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Klip"
});