tinyMCE.addI18n('eu.style_dlg',{
title:"Aldatu CSS estiloa",
apply:"Apply",
text_tab:"Testua",
background_tab:"Atzea",
block_tab:"Block",
box_tab:"Box",
border_tab:"Border",
list_tab:"Zerrenda",
positioning_tab:"Kokapena",
text_props:"Testua",
text_font:"Letra-tipoa",
text_size:"Tamaina",
text_weight:"Weight",
text_style:"Estiloa",
text_variant:"Aldaera",
text_lineheight:"Lerro garaiera",
text_case:"Case",
text_color:"Kolorea",
text_decoration:"Decoration",
text_overline:"overline",
text_underline:"underline",
text_striketrough:"strikethrough",
text_blink:"blink",
text_none:"none",
background_color:"Atzeko kolorea",
background_image:"Atzeko irudia",
background_repeat:"Errepikatu",
background_attachment:"Eranskina",
background_hpos:"Posizio horizontala",
background_vpos:"Posizio bertikala",
block_wordspacing:"Hitz banaketa",
block_letterspacing:"Letra banaketa",
block_vertical_alignment:"Lerrokatze bertikala",
block_text_align:"Testu lerrokatzea",
block_text_indent:"Text indent",
block_whitespace:"Zuriunea",
block_display:"Display",
box_width:"Zabalera",
box_height:"Altuera",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Guztientzat bera",
top:"Top",
right:"Right",
bottom:"Bottom",
left:"Ezkerrera",
margin:"Margin",
style:"Estiloa",
width:"Zabalera",
height:"Altuera",
color:"Kolorea",
list_type:"Mota",
bullet_image:"Buleta irudia",
position:"Kokapena",
positioning_type:"Mora",
visibility:"Ikusgarritasuna",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});