tinyMCE.addI18n('lb.style_dlg',{
title:"CSS-Styles beaarbechten",
apply:"Iwwerhuelen",
text_tab:"Text",
background_tab:"Hannergrond",
block_tab:"Block",
box_tab:"Box",
border_tab:"Rumm",
list_tab:"L\u00EBscht",
positioning_tab:"Position\u00E9ierung",
text_props:"Text",
text_font:"Schr\u00EBftaart",
text_size:"Gr\u00E9isst",
text_weight:"D\u00E9ckt",
text_style:"Stil",
text_variant:"Variant",
text_lineheight:"Zeilenh\u00E9icht",
text_case:"Schreiwung",
text_color:"Fuerf",
text_decoration:"Gestaltung",
text_overline:"iwwerstrach",
text_underline:"\u00EBnnerstrach",
text_striketrough:"duerchgestrach",
text_blink:"bl\u00EBnkend",
text_none:"keng",
background_color:"Hannergrondfuerf",
background_image:"Hannergrondbild",
background_repeat:"Widderhuelung",
background_attachment:"Waasserzeecheneffekt",
background_hpos:"Positioun X",
background_vpos:"Positioun Y",
block_wordspacing:"Wuertofstand",
block_letterspacing:"Buschtawenofstand",
block_vertical_alignment:"Vertikal Ausriichtung",
block_text_align:"Ausriichtung",
block_text_indent:"Ar\u00E9ckung",
block_whitespace:"Automateschen \u00CBmbroch",
block_display:"\u00CBmbrochverhalen",
box_width:"Breet",
box_height:"H\u00E9icht",
box_float:"\u00CBmfl\u00E9issung",
box_clear:"\u00CBmfl\u00E9issung verh\u00EBnneren",
padding:"Banneschten Ofstand",
same:"All selwecht",
top:"Uewen",
right:"Riets",
bottom:"\u00CBnnen",
left:"L\u00E9nks",
margin:"Baussechten Ofstand",
style:"Format",
width:"Breet",
height:"H\u00E9icht",
color:"Textfuerf",
list_type:"L\u00EBschtepunkt-Aart",
bullet_image:"L\u00EBschtepunkt-Grafik",
position:"Position\u00E9ierung",
positioning_type:"Aart vun der Position\u00E9ierung",
visibility:"Siichtbar",
zindex:"Z-W\u00E4ert",
overflow:"Verhale bei Iwwergr\u00E9isst",
placement:"Plaz\u00E9ierung",
clip:"Ausschn\u00EBtt"
});