tinyMCE.addI18n('no.style_dlg',{
title:"Rediger CSS-stil",
apply:"Bruk",
text_tab:"Tekst",
background_tab:"Bakgrunn",
block_tab:"Blokk",
box_tab:"Boks",
border_tab:"Ramme",
list_tab:"Liste",
positioning_tab:"Posisjon",
text_props:"Tekst",
text_font:"Skrifttype",
text_size:"Skriftst\u00F8rrelse",
text_weight:"Skriftvekt",
text_style:"Skriftstil",
text_variant:"Variant",
text_lineheight:"Linjeh\u00F8yde",
text_case:"Store/sm\u00E5 bokstaver",
text_color:"Farge",
text_decoration:"Dekorasjon",
text_overline:"Heve skrift",
text_underline:"Senke skrift",
text_striketrough:"Gjennomstreke",
text_blink:"Blinke",
text_none:"Ingen",
background_color:"Bakgrunnsfarge",
background_image:"Bakgrunnsbilde",
background_repeat:"Repetere",
background_attachment:"Vedlegg",
background_hpos:"Horisontal posisjon",
background_vpos:"Vertikal posisjon",
block_wordspacing:"Mellomrom",
block_letterspacing:"Bokstav mellomrom",
block_vertical_alignment:"Vertikal justering",
block_text_align:"Justering",
block_text_indent:"Innrykk",
block_whitespace:"Mellomrom",
block_display:"Visning",
box_width:"Bredde",
box_height:"H\u00F8yde",
box_float:"Flytende",
box_clear:"Slette",
padding:"Utfylling",
same:"Likt for alle",
top:"Topp",
right:"H\u00F8yre",
bottom:"Bunn",
left:"Venstre",
margin:"Marg",
style:"Stil",
width:"Bredde",
height:"H\u00F8yde",
color:"Farge",
list_type:"Type",
bullet_image:"Punkt bilde",
position:"Posisjon",
positioning_type:"Type",
visibility:"Synlighet",
zindex:"Z-indeks",
overflow:"Overfylt",
placement:"Plassering",
clip:"Klipp"
});