tinyMCE.addI18n('sk.style_dlg',{
title:"Upravi\u0165 CSS \u0161t\u00FDl",
apply:"Pou\u017Ei\u0165",
text_tab:"Text",
background_tab:"Pozadie",
block_tab:"Blok",
box_tab:"Box",
border_tab:"Or\u00E1movanie",
list_tab:"Zoznam",
positioning_tab:"Umiesnenie",
text_props:"Text",
text_font:"P\u00EDsmo",
text_size:"Ve\u013Ekos\u0165",
text_weight:"Tu\u010Dnos\u0165 p\u00EDsma",
text_style:"\u0160t\u00FDl textu",
text_variant:"Varianta",
text_lineheight:"V\u00FD\u0161ka riadkov",
text_case:"Ve\u013Ek\u00E9 p\u00EDsmen\u00E1",
text_color:"Farba",
text_decoration:"Dekor\u00E1cia",
text_overline:"nad\u010Diarknutie",
text_underline:"pod\u010Diarknutie",
text_striketrough:"pre\u010Diarknutie",
text_blink:"blikanie",
text_none:"\u017Eiadna",
background_color:"Farba pozadia",
background_image:"Obr\u00E1zok pozadia",
background_repeat:"Opakovanie",
background_attachment:"Rolovanie",
background_hpos:"Horizont\u00E1lne umiestnenie",
background_vpos:"Vertik\u00E1lne umiestnenie",
block_wordspacing:"Rozstup slov",
block_letterspacing:"Rozstup znakov",
block_vertical_alignment:"Vertik\u00E1lne zarovnanie",
block_text_align:"Zarovnanie textu",
block_text_indent:"Odsadenie textu",
block_whitespace:"Zalamovanie textu",
block_display:"Blokov\u00E9 zobrazenie",
box_width:"\u0160\u00EDrka",
box_height:"V\u00FD\u0161ka",
box_float:"Pl\u00E1vaj\u00FAci",
box_clear:"Vy\u010Disti\u0165",
padding:"Odsadenie (padding)",
same:"Rovnak\u00E9 pre v\u0161etky",
top:"Hore",
right:"Vpravo",
bottom:"Dole",
left:"V\u013Eavo",
margin:"Okraje (margin)",
style:"\u0160t\u00FDl",
width:"\u0160\u00EDrka",
height:"V\u00FD\u0161ka",
color:"Farba",
list_type:"Typ",
bullet_image:"\u0160t\u00FDl odr\u00E1\u017Eok",
position:"Umiestnenie",
positioning_type:"Typ",
visibility:"Vidite\u013Enos\u0165",
zindex:"Z-index",
overflow:"Prete\u010Denie (overflow)",
placement:"Umiestnenie",
clip:"Orezanie (clip)"
});