tinyMCE.addI18n('tr.style_dlg',{
title:"CSS Stilini D\u00FCzenle",
apply:"Uygula",
text_tab:"Metin",
background_tab:"Arkaplan",
block_tab:"Blok",
box_tab:"Kutu",
border_tab:"Kenarl\u0131k",
list_tab:"Listele",
positioning_tab:"Konumland\u0131rma",
text_props:"Metin",
text_font:"Yaz\u0131 tipi",
text_size:"Boyut",
text_weight:"Kal\u0131nl\u0131k",
text_style:"Stil",
text_variant:"De\u011Fi\u015Fken",
text_lineheight:"\u00C7izgi y\u00FCksekli\u011Fi",
text_case:"Ko\u015Ful",
text_color:"Renk",
text_decoration:"Dekorasyon",
text_overline:"\u00FCst \u00E7izgi",
text_underline:"alt \u00E7izgi",
text_striketrough:"\u00FCst\u00FC \u00E7izgili",
text_blink:"yan\u0131p s\u00F6nen",
text_none:"hi\u00E7biri",
background_color:"Arkaplan rengi",
background_image:"Arkaplan resmi",
background_repeat:"Tekrarla",
background_attachment:"Eklenti",
background_hpos:"Yatay konum",
background_vpos:"Dikey konum",
block_wordspacing:"Kelime bo\u015Flu\u011Fu",
block_letterspacing:"harf bo\u015Flu\u011Fu",
block_vertical_alignment:"Dikey hizalama",
block_text_align:"Metin hizala",
block_text_indent:"Metnin girintisini art\u0131r",
block_whitespace:"Bo\u015Fluk",
block_display:"G\u00F6r\u00FCnt\u00FCle",
box_width:"Geni\u015Flik",
box_height:"Y\u00FCkseklik",
box_float:"Kayan",
box_clear:"Serbest",
padding:"Dolgu",
same:"T\u00FCm\u00FC i\u00E7in",
top:"\u00DCst",
right:"Sa\u011F",
bottom:"Alt",
left:"Sol",
margin:"Kenar bo\u015Flu\u011Fu",
style:"Stil",
width:"Geni\u015Flik",
height:"Y\u00FCkseklik",
color:"Renk",
list_type:"Tip",
bullet_image:"Madde imi resmi",
position:"Konum",
positioning_type:"Tip",
visibility:"G\u00F6r\u00FCn\u00FCrl\u00FCk",
zindex:"Z-indeksi",
overflow:"Ta\u015Fma",
placement:"Yerle\u015Ftir",
clip:"K\u0131rp"
});