tinyMCE.addI18n('no.advimage_dlg',{
tab_general:"Generelt",
tab_appearance:"Utseende",
tab_advanced:"Avansert",
general:"Generelt",
title:"Tittel",
preview:"Forh\u00E5ndsvisning",
constrain_proportions:"Behold proporsjoner",
langdir:"Skriftretning",
langcode:"Spr\u00E5k kode",
long_desc:"Lang beskrivelse",
style:"Stil",
classes:"Klasse",
ltr:"Venstre mot h\u00F8yre",
rtl:"H\u00F8yre mot venstre",
id:"Id",
map:"Bildekart",
swap_image:"Bytt bilde",
alt_image:"Alternativt bilde",
mouseover:"for musepeker over",
mouseout:"for musepeker utenfor",
misc:"Diverse",
example_img:"Utseende forh\u00E5ndsvisning",
missing_alt:"Er du sikker du vil fortsette uten \u00E5 sette inn bildebeskrivelse? Uten beskrivelse vil ikke bildet gi mening for enkelte funksjonshemmde eller personer som bruker nettleser med avsl\u00E5tt bildevising.",
dialog_title:"Sett inn/editer bilde",
src:"Bilde URL",
alt:"Bildebeskrivelse",
list:"Bildeliste",
border:"Ramme",
dimensions:"Dimensjoner",
vspace:"Vertikal avstand",
hspace:"Horisontal avstand",
align:"Justering",
align_baseline:"Basislinje",
align_top:"Topp",
align_middle:"Midtstilt",
align_bottom:"Bunn",
align_texttop:"Tekst topp",
align_textbottom:"Tekst bunn",
align_left:"Venstre",
align_right:"H\u00F8yre",
image_list:"Liste over bilder"
});