tinyMCE.addI18n('cs.fullpage_dlg',{
title:"Vlastnosti dokumentu",
meta_tab:"Obecn\u00E9",
appearance_tab:"Vzhled",
advanced_tab:"Roz\u0161\u00ED\u0159en\u00E9",
meta_props:"Meta informace",
langprops:"Jazyk a k\u00F3dov\u00E1n\u00ED",
meta_title:"Titulek",
meta_keywords:"Kl\u00ED\u010Dov\u00E1 slova",
meta_description:"Popis",
meta_robots:"Roboti",
doctypes:"Typ dokumentu",
langcode:"K\u00F3d jazyka",
langdir:"Sm\u011Br textu",
ltr:"Zleva doprava",
rtl:"Zprava doleva",
xml_pi:"XML deklarace",
encoding:"K\u00F3dov\u00E1n\u00ED",
appearance_bgprops:"Vlastnosti pozad\u00ED",
appearance_marginprops:"Okraje t\u011Bla dokumentu",
appearance_linkprops:"Vlastnosti odkaz\u016F",
appearance_textprops:"Vlastnosti textu",
bgcolor:"Barva pozad\u00ED",
bgimage:"Obr\u00E1zek pozad\u00ED",
left_margin:"Lev\u00FD okraj",
right_margin:"Prav\u00FD okraj",
top_margin:"Horn\u00ED okraj",
bottom_margin:"Spodn\u00ED okraj",
text_color:"Barva textu",
font_size:"Velikost p\u00EDsma",
font_face:"Typ p\u00EDsma",
link_color:"Barva odkazu",
hover_color:"Barva zvolen\u00E9ho odkazu",
visited_color:"Barva nav\u0161t\u00EDven\u00E9ho odkazu",
active_color:"Barva aktivn\u00EDho odkazu",
textcolor:"Barva",
fontsize:"Velikost p\u00EDsma",
fontface:"Typ p\u00EDsma",
meta_index_follow:"Indexovat a sledovat odkazy",
meta_index_nofollow:"Indexovat a nesledovat odkazy",
meta_noindex_follow:"Neindexovat, ale sledovat odkazy",
meta_noindex_nofollow:"Neindexovat a nesledovat odkazy",
appearance_style:"Vlastnosti styl\u016F",
stylesheet:"Stylopis",
style:"Styl",
author:"Autor",
copyright:"Autorsk\u00E1 pr\u00E1va",
add:"P\u0159idat nov\u00FD element",
remove:"Odebrat ozna\u010Den\u00FD element",
moveup:"P\u0159esu\u0148 ozna\u010Den\u00FD element v\u00FD\u0161",
movedown:"P\u0159esu\u0148 ozna\u010Den\u00FD element n\u00ED\u017E",
head_elements:"Hlavi\u010Dky",
info:"Informace",
add_title:"Vlo\u017Eit titulek",
add_meta:"Vlo\u017Eit meta informace",
add_script:"Vlo\u017Eit skript",
add_style:"Vlo\u017Eit styl",
add_link:"Vlo\u017Eit nezobrazovan\u00FD odkaz",
add_base:"Vlo\u017Eit z\u00E1kladn\u00ED um\u00EDst\u011Bn\u00ED",
add_comment:"Vlo\u017Eit koment\u00E1\u0159",
title_element:"Titulek",
script_element:"Skript",
style_element:"Styl",
base_element:"Z\u00E1kladn\u00ED um\u00EDst\u011Bn\u00ED",
link_element:"Nezobrazovan\u00FD odkaz",
meta_element:"Meta informace",
comment_element:"Koment\u00E1\u0159",
src:"Zdroj",
language:"Jazyk",
href:"Soubor/URL",
target:"C\u00EDl",
type:"Typ",
charset:"Znakov\u00E1 sada",
defer:"Odlo\u017Eit (defer)",
media:"M\u00E9dia",
properties:"Vlastnosti",
name:"N\u00E1zev",
value:"Hodnota",
content:"Obsah",
rel:"Vztah str\u00E1nky k c\u00EDli",
rev:"Vztah c\u00EDle ke str\u00E1nce",
hreflang:"Jazyk odkazu",
general_props:"Obecn\u00E9 parametry",
advanced_props:"Roz\u0161\u00ED\u0159en\u00E9 parametry"
});