tinyMCE.addI18n('no.advlink_dlg',{
title:"Sett inn/editer lenke",
url:"Lenke URL",
target:"M\u00E5l",
titlefield:"Tittel",
is_email:"URLen du skrev inn ser ut til \u00E5 v\u00E6re Epost adresse. \u00D8nsker du \u00E5 legge til obligatorisk mailto:-prefiks?",
is_external:"URLen du skrev inn ser ut til \u00E5 v\u00E6re en ekstern lenke. \u00D8nsker du \u00E5 legge til obligatorisk http://-prefiks?",
list:"Liste over lenker",
general_tab:"Generelt",
popup_tab:"Popup",
events_tab:"Hendelser",
advanced_tab:"Avansert",
general_props:"Generelle egenskaper",
popup_props:"Popup egenskaper",
event_props:"Hendelser",
advanced_props:"Avanserte egenskaper",
popup_opts:"Innstillinger",
anchor_names:"Anker",
target_same:"\u00C5pne i samme vindu/ramme",
target_parent:"\u00C5pne i overordnet vindu/ramme",
target_top:"\u00C5pne i toppvindu (erstatter alle rammer)",
target_blank:"\u00C5pne i nytt vindu",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Navn p\u00E5 vindu",
popup_return:"Sett inn \'return false\'",
popup_scrollbars:"Vis rullefelt",
popup_statusbar:"Vis statusline",
popup_toolbar:"Vis verkt\u00F8ylinjer",
popup_menubar:"Vis menylinje",
popup_location:"Vis plasseringslinje",
popup_resizable:"Gj\u00F8r vinduet skalerbart",
popup_dependent:"Avhengig vindu (kun i Mozilla/Firefox)",
popup_size:"St\u00F8rrelse",
popup_position:"Posisjon (X/Y)",
id:"Id",
style:"Stil",
classes:"Klasse",
target_name:"M\u00E5lnavn",
langdir:"Skriftretning",
target_langcode:"M\u00E5lspr\u00E5k",
langcode:"Spr\u00E5kkode",
encoding:"M\u00E5l karakter koding",
mime:"M\u00E5l MIME type",
rel:"Forholdet mellom side og m\u00E5l",
rev:"Forholdet mellom m\u00E5l og side",
tabindex:"Tabulator indeks",
accesskey:"Hurtigtast",
ltr:"Venstre mot h\u00F8yre",
rtl:"H\u00F8yre mot venstre",
link_list:"Liste over lenker"
});