# Generated by Django 2.2.17 on 2021-01-28 10:51

from django.db import migrations, models

import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("foobar", tinymce.models.HTMLField()),
            ],
        ),
    ]
