tinyMCE.addI18n('no.xhtmlxtras_dlg',{
attribute_label_title:"Tittel",
attribute_label_id:"ID",
attribute_label_class:"Klasse",
attribute_label_style:"Stil",
attribute_label_cite:"Sted",
attribute_label_datetime:"Dato/tid",
attribute_label_langdir:"Tekstretning",
attribute_option_ltr:"Venstre mot h\u00F8yre",
attribute_option_rtl:"H\u00F8yre mot venstre",
attribute_label_langcode:"Spr\u00E5k",
attribute_label_tabindex:"Tab indeks",
attribute_label_accesskey:"Tilgangsn\u00F8kkel",
attribute_events_tab:"Hendelser",
attribute_attrib_tab:"Attributter",
general_tab:"Generelt",
attrib_tab:"Attributter",
events_tab:"Hendelser",
fieldset_general_tab:"Generelle innstillinger",
fieldset_attrib_tab:"Element attributter",
fieldset_events_tab:"Element hendelser",
title_ins_element:"Innsetting element",
title_del_element:"Slette element",
title_acronym_element:"Akronym element",
title_abbr_element:"Forkorting element",
title_cite_element:"Sitat element",
remove:"Fjerne",
insert_date:"Sett inn dato/tid",
option_ltr:"Venstre mot h\u00F8yre",
option_rtl:"H\u00F8yre mot venstre",
attribs_title:"Sett inn/editer attributt"
});