tinyMCE.addI18n('no.table_dlg',{
general_tab:"Generelt",
advanced_tab:"Avansert",
general_props:"Generelle egenskaper",
advanced_props:"Avanserte egenskaper",
rowtype:"Rad i tabell",
title:"Sett inn/editer tabell",
width:"Bredde",
height:"H\u00F8yde",
cols:"Kolonner",
rows:"Rader",
cellspacing:"Celleavstand",
cellpadding:"Cellefylling",
border:"Ramme",
align:"Justering",
align_default:"Standard",
align_left:"Venstre",
align_right:"H\u00F8yre",
align_middle:"Midtstilt",
row_title:"Rad egenskaper",
cell_title:"Celle egenskaper",
cell_type:"Celle type",
valign:"Vertikal justering",
align_top:"Topp",
align_bottom:"Bunn",
bordercolor:"Rammefarge",
bgcolor:"Bakgrunnsfarge",
merge_cells_title:"Sl\u00E5 sammen celler",
id:"Id",
style:"Stil",
langdir:"Skriftretning",
langcode:"Spr\u00E5k kode",
mime:"M\u00E5lets MIME-type",
ltr:"Venstre mot h\u00F8yre",
rtl:"H\u00F8yre mot venstre",
bgimage:"Bakgrunnsbilde",
summary:"Sammendrag",
td:"Data",
th:"Overskrift",
cell_cell:"Oppdater aktuell celle",
cell_row:"Oppdater alle celler i raden",
cell_all:"Oppdater alle celler i tabellen",
row_row:"Oppdater aktuell rad",
row_odd:"Oppdater rader med oddetall",
row_even:"Oppdater rader med partall",
row_all:"Oppdater alle rader",
thead:"Tabell head",
tbody:"Tabell body",
tfoot:"Tabell foot",
scope:"Tittel",
rowgroup:"Rad gruppe",
colgroup:"Kolonne gruppe",
col_limit:"Du har overg\u00E5tt maksimalt antall tillatte kolonner p\u00E5 {$cols}.",
row_limit:"Du har overg\u00E5tt maksimalt antall tillatte rader p\u00E5 {$rows}.",
cell_limit:"Du har overg\u00E5tt maksimalt antall tillatt celler p\u00E5 {$cells}.",
missing_scope:"Er du sikker du vil fortsette uten \u00E5 angi tittel for denne overskrifscellen? Uten denne kan det bli vanskelig for enkelte funksjonshemmede brukere \u00E5 forst\u00E5 innhold eller data som presenteres i tabellen.",
caption:"Tabell tittel",
frame:"Ramme",
frame_none:"ingen",
frame_groups:"grupper",
frame_rows:"rader",
frame_cols:"kolonner",
frame_all:"alle",
rules:"Streker",
rules_void:"tom",
rules_above:"over",
rules_below:"under",
rules_hsides:"hside",
rules_lhs:"vs",
rules_rhs:"hs",
rules_vsides:"vside",
rules_box:"boks",
rules_border:"ramme"
});