# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testinline',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtinymce.TestPage'),
        ),
    ]
